# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: gitgraph
    main: .
    binary: gitgraph
    ldflags:
      - -s -w
      - -X GitGraph/cmd.version={{.Version}}
      - -X GitGraph/cmd.commit={{.Commit}}
      - -X GitGraph/cmd.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: gitgraph-archive
    formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE*
      - README*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci"
      - "^chore"
release:
  github:
    owner: woidthevoid
    name: gitgraph
  draft: false
  prerelease: auto